# Generated by Django 5.2.5 on 2025-09-11 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBotEngine', '0002_conversation_message_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentinstruction',
            options={'ordering': ['title'], 'verbose_name': 'Chatbot', 'verbose_name_plural': 'Chatbots'},
        ),
        migrations.AddField(
            model_name='agentinstruction',
            name='owner',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, related_name='chatbots', to=settings.AUTH_USER_MODEL),
        ),
    ]
