# Generated by Django 5.2.5 on 2025-09-15 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBotEngine', '0003_alter_agentinstruction_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agentinstruction',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Accessible à tous les utilisateurs connectés si activé.'),
        ),
        migrations.AddField(
            model_name='agentinstruction',
            name='shared_with',
            field=models.ManyToManyField(blank=True, help_text='Utilisateurs spécifiques avec lesquels ce ChatBot est partagé.', related_name='chatbots_shared_with_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agentinstruction',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chatbots', to=settings.AUTH_USER_MODEL),
        ),
    ]
