# Generated by Django 5.2.5 on 2025-09-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBotEngine', '0004_agentinstruction_is_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentinstruction',
            name='enable_image_tool',
            field=models.BooleanField(default=False, help_text='Si désactivé, le tool image_generation ne sera pas transmis à Mistral', verbose_name="Activer la génération d'images"),
        ),
    ]
