# Generated by Django 5.2.5 on 2025-09-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBotEngine', '0005_agentinstruction_enable_image_tool'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentinstruction',
            name='enable_web_search',
            field=models.BooleanField(default=False, verbose_name='Autoriser la recherche web'),
        ),
    ]
