# Generated by Django 5.2.5 on 2025-10-01 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBotEngine', '0006_agentinstruction_enable_web_search'),
        ('core', '0008_fileasset_tokens_logged'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agentinstruction',
            name='enable_file_upload',
            field=models.BooleanField(default=False, help_text='Si désactivé, l’utilisateur ne pourra pas joindre de fichier dans ses conversations avec cet agent.', verbose_name='Autoriser le dépôt de fichiers'),
        ),
        migrations.CreateModel(
            name='ConversationFileAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attached_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='ChatBotEngine.conversation')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_conversations', to='core.fileasset')),
            ],
            options={
                'verbose_name': 'Fichier attaché à une conversation',
                'verbose_name_plural': 'Fichiers attachés à des conversations',
            },
        ),
        migrations.CreateModel(
            name='AgentFileLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_files', to='ChatBotEngine.agentinstruction')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_agents', to='core.fileasset')),
            ],
            options={
                'verbose_name': 'Fichier associé à un agent',
                'verbose_name_plural': 'Fichiers associés à des agents',
                'unique_together': {('agent', 'file')},
            },
        ),
    ]
