# Generated by Django 5.2.5 on 2025-10-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBotEngine', '0007_agentinstruction_enable_file_upload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='mistral_conversation_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
