# Generated by Django 5.2.5 on 2025-10-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBotEngine', '0008_conversation_mistral_conversation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentinstruction',
            name='mistral_library_id',
            field=models.CharField(blank=True, help_text='ID de la librairie Mistral dédiée à cet agent.', max_length=255, null=True),
        ),
    ]
