# Generated by Django 5.2.5 on 2025-10-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBotEngine', '0009_agentinstruction_mistral_library_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentinstruction',
            name='mistral_agent_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID de l’agent persistant chez Mistral.', max_length=128, null=True),
        ),
    ]
