# Generated by Django 5.2.5 on 2025-10-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBotEngine', '0010_agentinstruction_mistral_agent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='mistral_library_id',
            field=models.CharField(blank=True, help_text='Library Mistral dédiée à cette conversation (scopée).', max_length=255, null=True),
        ),
    ]
