# Generated by Django 5.2.5 on 2025-10-28 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBotEngine', '0011_conversation_mistral_library_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentinstruction',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Date de péremption pour les agents temporaires (purge automatique).', null=True),
        ),
        migrations.AddField(
            model_name='agentinstruction',
            name='is_temporary',
            field=models.BooleanField(default=False, help_text='True si cet agent est un clone temporaire (lié à une conversation utilisateur).'),
        ),
        migrations.AddField(
            model_name='agentinstruction',
            name='source_agent',
            field=models.ForeignKey(blank=True, help_text='Agent d’origine si cet agent est un clone temporaire.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='ChatBotEngine.agentinstruction'),
        ),
    ]
