# Generated by Django 5.2.5 on 2025-10-29 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBotEngine', '0012_agentinstruction_expires_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='mistral_library_id',
        ),
        migrations.DeleteModel(
            name='ConversationFileAttachment',
        ),
    ]
