# Generated by Django 5.2.5 on 2025-11-06 13:28

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ("ChatBotEngine", "0013_remove_conversation_mistral_library_id_and_more"),
    ]

    operations = []
