# Generated by Django 5.2.5 on 2025-11-06 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBotEngine', '0014_add_source_agent_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentinstruction',
            name='source_agent',
            field=models.ForeignKey(blank=True, help_text='Agent d’origine si cet agent est un clone temporaire.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='ChatBotEngine.agentinstruction'),
        ),
    ]
