# Generated by Django 5.2.5 on 2025-11-06 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBotEngine', '0015_alter_agentinstruction_source_agent'),
        ('ChatBotEngine', '0016_add_is_temporary_field'),
    ]

    operations = [
    ]
