# Generated by Django 5.2.5 on 2026-01-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBotEngine', '0019_alter_agentinstruction_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentinstruction',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Date de péremption pour les agents temporaires (purge automatique).', null=True),
        ),
        migrations.AlterField(
            model_name='agentinstruction',
            name='is_temporary',
            field=models.BooleanField(default=False, help_text='True si cet agent est un clone temporaire (lié à une conversation utilisateur).'),
        ),
    ]
