# Generated by Django 5.2.5 on 2025-09-04 13:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_delete_pendingregistration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('source_app', models.CharField(db_index=True, max_length=100)),
                ('source_module', models.CharField(blank=True, default='', help_text='Vue/Job/Task optionnel', max_length=150)),
                ('provider', models.CharField(default='mistral', max_length=50)),
                ('model', models.CharField(max_length=120)),
                ('tokens_input', models.PositiveIntegerField(default=0)),
                ('tokens_output', models.PositiveIntegerField(default=0)),
                ('tokens_total', models.PositiveIntegerField(default=0)),
                ('cost_eur', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('co2_grams', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('request_hash', models.CharField(blank=True, db_index=True, default='', help_text='Hash du prompt (pas de stockage en clair)', max_length=128)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error')], default='success', max_length=20)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'source_app'], name='core_aicall_timesta_21954e_idx'), models.Index(fields=['user', 'timestamp'], name='core_aicall_user_id_30d9cd_idx'), models.Index(fields=['model'], name='core_aicall_model_e0e62b_idx')],
            },
        ),
    ]
