# Generated by Django 5.2.5 on 2025-09-29 15:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_fileasset_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileasset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
