# Generated by Django 5.2.5 on 2025-09-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_fileasset_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileasset',
            name='number_of_pages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fileasset',
            name='processing_status',
            field=models.CharField(default='Running', max_length=20),
        ),
        migrations.AddField(
            model_name='fileasset',
            name='tokens_processing_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
