# Generated by Django 5.2.5 on 2025-10-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_fileasset_number_of_pages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileasset',
            name='tokens_logged',
            field=models.BooleanField(default=False),
        ),
    ]
