# Generated by Django 5.2.5 on 2025-11-05 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_fileasset_tokens_logged'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='mistral_library_id',
        ),
    ]
