# Generated by Django 5.2.5 on 2025-12-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_userprofile_mistral_library_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_logement_admin',
            field=models.BooleanField(default=False),
        ),
    ]
