# Generated by Django 5.2.5 on 2026-01-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_userprofile_is_logement_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_logement_admin',
            field=models.BooleanField(default=False, help_text='DEPRECATED: remplacé par DomaineUser.is_admin (admin par domaine).'),
        ),
    ]
