# Generated by Django 5.2.5 on 2026-01-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_userprofile_is_logement_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_plateforme_admin',
            field=models.BooleanField(default=False, help_text='Administrateur de la plateforme (domaines, canaux, salutations).'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_logement_admin',
            field=models.BooleanField(default=False, help_text='DEPRECATED: compatibilité legacy (à supprimer à terme).'),
        ),
    ]
