# Generated by Django 5.2.5 on 2026-01-08 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_userprofile_is_plateforme_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_logement_admin',
        ),
    ]
