# Generated by Django 5.2.5 on 2025-11-27 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Demandeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('num_unique', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thematique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('libelle_thematique', models.CharField(max_length=255, unique=True)),
                ('reponse_type', models.TextField()),
            ],
            options={
                'verbose_name': 'Thématique',
                'verbose_name_plural': 'Thématiques',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ContactEntrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('objet', models.TextField(blank=True, null=True)),
                ('txtdemande', models.TextField()),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logement.canal')),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacts_entrants', to='logement.demandeur')),
                ('thematiques', models.ManyToManyField(blank=True, related_name='contacts_entrants', to='logement.thematique')),
            ],
        ),
    ]
