# Generated by Django 5.2.5 on 2025-11-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logement', '0002_contactentrant_created_at_contactentrant_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactentrant',
            name='reponse',
            field=models.TextField(blank=True, null=True),
        ),
    ]
