# Generated by Django 5.2.5 on 2025-12-03 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logement', '0003_contactentrant_reponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatutContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='contactentrant',
            name='statut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contacts_entrants', to='logement.statutcontact'),
        ),
    ]
