# Generated by Django 5.2.5 on 2025-12-10 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logement', '0004_statutcontact_contactentrant_statut'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thematique',
            options={'ordering': ['parent__id', 'ordre', 'libelle_thematique'], 'verbose_name': 'Thématique', 'verbose_name_plural': 'Thématiques'},
        ),
        migrations.RemoveField(
            model_name='thematique',
            name='code',
        ),
        migrations.AddField(
            model_name='thematique',
            name='ordre',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='thematique',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enfants', to='logement.thematique'),
        ),
    ]
