# Generated by Django 5.2.5 on 2025-12-10 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logement', '0005_alter_thematique_options_remove_thematique_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255, unique=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordre', 'libelle'],
            },
        ),
        migrations.AlterModelOptions(
            name='thematique',
            options={'ordering': ['groupe__domaine__ordre', 'groupe__ordre', 'ordre', 'libelle_thematique']},
        ),
        migrations.RemoveField(
            model_name='thematique',
            name='parent',
        ),
        migrations.AlterField(
            model_name='thematique',
            name='libelle_thematique',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='thematique',
            name='reponse_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('domaine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groupes', to='logement.domaine')),
            ],
            options={
                'ordering': ['domaine__ordre', 'ordre', 'libelle'],
            },
        ),
        migrations.AddField(
            model_name='thematique',
            name='groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thematiques', to='logement.groupe'),
        ),
    ]
