# Generated by Django 5.2.5 on 2025-12-10 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logement', '0006_domaine_alter_thematique_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupe',
            name='domaine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupes', to='logement.domaine'),
        ),
        migrations.AlterField(
            model_name='thematique',
            name='groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thematiques', to='logement.groupe'),
        ),
    ]
