# Generated by Django 5.2.5 on 2025-12-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logement', '0007_alter_groupe_domaine_alter_thematique_groupe'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupe',
            name='collapsed_by_default',
            field=models.BooleanField(default=False),
        ),
    ]
