# Generated by Django 5.2.5 on 2025-12-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logement', '0008_groupe_collapsed_by_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='thematique',
            name='cocher_par_defaut',
            field=models.BooleanField(default=False),
        ),
    ]
