# Generated by Django 5.2.5 on 2025-12-11 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logement', '0009_thematique_cocher_par_defaut'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactentrant',
            name='domaine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contacts_entrants', to='logement.domaine'),
        ),
    ]
