# Generated by Django 5.2.5 on 2025-12-11 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logement', '0010_contactentrant_domaine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactentrant',
            name='domaine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacts_entrants', to='logement.domaine'),
        ),
    ]
