# Generated by Django 5.2.5 on 2025-12-11 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logement', '0011_alter_contactentrant_domaine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salutations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ['libelle'],
            },
        ),
        migrations.AddField(
            model_name='contactentrant',
            name='salutation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts_entrants', to='logement.salutations'),
        ),
    ]
