# Generated by Django 5.2.5 on 2025-12-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logement', '0012_salutations_contactentrant_salutation'),
    ]

    operations = [
        migrations.AddField(
            model_name='domaine',
            name='agent_id',
            field=models.CharField(blank=True, help_text='Identifiant de l’agent Mistral permettant de rédiger les mails', max_length=64, null=True),
        ),
    ]
