# Generated by Django 5.2.5 on 2025-12-18 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBotEngine', '0019_alter_agentinstruction_expires_at_and_more'),
        ('logement', '0013_domaine_agent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domaine',
            name='agent_id',
        ),
        migrations.AddField(
            model_name='domaine',
            name='agent',
            field=models.ForeignKey(blank=True, help_text='Agent IA utilisé pour la rédaction automatique des mails', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domaines', to='ChatBotEngine.agentinstruction'),
        ),
    ]
