# Generated by Django 5.2.5 on 2025-12-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logement', '0014_remove_domaine_agent_id_domaine_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='domaine',
            name='signature',
            field=models.TextField(blank=True, help_text='Signature ajoutée automatiquement à la fin des emails sortants'),
        ),
    ]
