# Generated by Django 5.2.5 on 2026-01-08 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logement', '0015_domaine_signature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DomaineUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False, help_text='Administrateur fonctionnel de ce domaine (Groupes/Thématiques).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_links', to='logement.domaine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logement_domaines_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['domaine__ordre', 'domaine__libelle', 'user__username'],
                'constraints': [models.UniqueConstraint(fields=('user', 'domaine'), name='uniq_user_domaine')],
            },
        ),
    ]
