# Generated by Django 5.2.5 on 2026-01-11 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logement', '0016_domaineuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='domaine',
            name='intro',
            field=models.TextField(blank=True, help_text='Texte introductif ajoutée automatiquement au début des emails'),
        ),
        migrations.AlterField(
            model_name='domaine',
            name='signature',
            field=models.TextField(blank=True, help_text='Signature ajoutée automatiquement à la fin des emails'),
        ),
    ]
