# Generated by Django 5.2.5 on 2026-01-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logement', '0017_domaine_intro_alter_domaine_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='domaine',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Domaine accessible à tous les utilisateurs de la plateforme'),
        ),
    ]
