# Generated by Django 5.2.5 on 2026-02-11 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logement', '0019_contactentrant_evaluation_reponse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactentrant',
            name='external_message_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='PieceJointeContactEntrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_original', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=127)),
                ('taille', models.PositiveIntegerField(blank=True, null=True)),
                ('contenu', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact_entrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='logement.contactentrant')),
            ],
        ),
    ]
