# Generated by Django 5.2.5 on 2026-02-19 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logement", "0020_contactentrant_external_message_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlacklistedSender",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("entry_type", models.CharField(choices=[("email", "Adresse email"), ("domain", "Domaine")], max_length=10)),
                ("value", models.CharField(db_index=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logement_blacklist_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["entry_type", "value"],
            },
        ),
        migrations.AddConstraint(
            model_name="blacklistedsender",
            constraint=models.UniqueConstraint(fields=("entry_type", "value"), name="uniq_blacklisted_sender_type_value"),
        ),
    ]
