# Generated by Django 5.2.5 on 2026-02-19 12:35

import django.db.models.deletion
from django.db import migrations, models


def _assign_domain_to_existing_blacklist_entries(apps, schema_editor):
    BlacklistedSender = apps.get_model("logement", "BlacklistedSender")
    Domaine = apps.get_model("logement", "Domaine")
    DomaineUser = apps.get_model("logement", "DomaineUser")

    first_domain = Domaine.objects.order_by("ordre", "id").first()
    if first_domain is None:
        return

    for entry in BlacklistedSender.objects.filter(domaine__isnull=True).iterator():
        assigned_domain = None
        if entry.created_by_id:
            user_domain_link = (
                DomaineUser.objects
                .filter(user_id=entry.created_by_id)
                .select_related("domaine")
                .order_by("domaine__ordre", "domaine_id")
                .first()
            )
            if user_domain_link:
                assigned_domain = user_domain_link.domaine

        entry.domaine_id = (assigned_domain.id if assigned_domain else first_domain.id)
        entry.save(update_fields=["domaine"])


class Migration(migrations.Migration):

    dependencies = [
        ("logement", "0021_blacklistedsender"),
    ]

    operations = [
        migrations.AddField(
            model_name="blacklistedsender",
            name="domaine",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blacklisted_senders",
                to="logement.domaine",
            ),
        ),
        migrations.RunPython(_assign_domain_to_existing_blacklist_entries, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="blacklistedsender",
            name="domaine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blacklisted_senders",
                to="logement.domaine",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="blacklistedsender",
            name="uniq_blacklisted_sender_type_value",
        ),
        migrations.AddConstraint(
            model_name="blacklistedsender",
            constraint=models.UniqueConstraint(
                fields=("domaine", "entry_type", "value"),
                name="uniq_blacklisted_sender_domain_type_value",
            ),
        ),
        migrations.AlterModelOptions(
            name="blacklistedsender",
            options={"ordering": ["domaine__ordre", "domaine__libelle", "entry_type", "value"]},
        ),
    ]
