# Generated by Django 5.2.5 on 2026-03-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logement", "0022_blacklist_domain_scope"),
    ]

    operations = [
        migrations.AddField(
            model_name="demandeur",
            name="nom",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
