"""
Django settings for Massy Innove project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""


import os
from pathlib import Path
from dotenv import load_dotenv, find_dotenv
from django.core.exceptions import ImproperlyConfigured

BASE_DIR = Path(__file__).resolve().parent.parent  # -> /.../src

# Trouver .env explicitement, et échouer bruyamment s'il est absent
env_path = find_dotenv(str(BASE_DIR / ".env"), raise_error_if_not_found=True)
load_dotenv(env_path, override=True)  # override=True pour écraser des valeurs vides du shell

SECRET_KEY = os.getenv("SECRET_KEY")
if not SECRET_KEY:
    raise ImproperlyConfigured("SECRET_KEY manquant. A définir dans le fichier .env")

raw_hosts = os.getenv("ALLOWED_HOSTS")
if not raw_hosts:
    raise ImproperlyConfigured("ALLOWED_HOSTS manquant. Définis-le dans ton .env")
ALLOWED_HOSTS = [h.strip() for h in raw_hosts.split(",") if h.strip()]






# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True




# Application definition

INSTALLED_APPS = [
    'core.apps.CoreConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.sites',
    'django.contrib.staticfiles',
    'allauth',
    'allauth.account',
    'ChatBotEngine.apps.ChatBotEngineConfig',
    'AssistantCR.apps.AssistantCRConfig',
    'logement.apps.LogementConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.LoginRequiredMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'core.middleware.ForceParisTZMiddleware',
]

ROOT_URLCONF = 'MassyInnove.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'MassyInnove' / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'MassyInnove.wsgi.application'


# Database

import pymysql
pymysql.install_as_MySQLdb()

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DATABASE_NAME'),
        'USER': os.getenv('DATABASE_USER'),
        'PASSWORD': os.getenv('DATABASE_PASSWORD'),
        'HOST': os.getenv('DATABASE_HOST'),
        'PORT': os.getenv('DATABASE_PORT'),
        'OPTIONS': {
            'charset': 'utf8mb4',
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES', time_zone='+00:00'",
            "use_unicode": True,
        }
    }
}

CONN_MAX_AGE = 0

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Gestion des logs

# Créer le répertoire logs s'il n'existe pas
log_dir = os.path.join(BASE_DIR, 'logs')
if not os.path.exists(log_dir):
    os.makedirs(log_dir)

log_file = os.path.join(log_dir, 'django_debug.log')

# Configuration de la journalisation
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': log_file,
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'TestIA': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}



# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'fr-FR'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# Récupérer la clé API Mistral AI depuis les variables d'environnement
MISTRAL_API_KEY = os.getenv('MISTRAL_API_KEY')

# Configuration des sessions

SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Utilise la base de données pour stocker les sessions
SESSION_COOKIE_AGE = 1209600  # Durée de vie du cookie de session en secondes (2 semaines par défaut)
SESSION_SAVE_EVERY_REQUEST = True  # Sauvegarde la session à chaque requête
SESSION_COOKIE_SECURE = True  # Assure que le cookie de session est envoyé uniquement via HTTPS
SESSION_COOKIE_HTTPONLY = True  # Empêche l'accès au cookie de session via JavaScript
SESSION_COOKIE_SAMESITE = 'Lax'  # Configure le cookie SameSite pour la sécurité

# Static files

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [
    BASE_DIR / "static",                 # ← dossier source
]
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Pour la gestion des fichiers utilisateurs

MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"



# Pour ALLAUTH

SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

# Pas de username, on s’authentifie uniquement par email
ACCOUNT_USER_MODEL_USERNAME_FIELD = "username"
ACCOUNT_UNIQUE_EMAIL = True

# Nouvelle syntaxe (Allauth 65+) + forcer le username
ACCOUNT_ADAPTER = "core.adapters.NoUsernameAccountAdapter"
ACCOUNT_LOGIN_METHODS = {"email"}   # login uniquement par email
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]  # email + mot de passe requis

# Formulaire custom (uniquement pour valider l'email du domaine)
ACCOUNT_FORMS = {
    "signup": "core.forms.CustomSignupForm",
}

ACCOUNT_EMAIL_VERIFICATION = "mandatory"   # email doit être confirmé

# Redirections
LOGIN_URL = "account_login"
LOGIN_REDIRECT_URL = "/"
ACCOUNT_LOGOUT_REDIRECT_URL = "/"

# Confort utilisateur
ACCOUNT_AUTHENTICATED_LOGIN_REDIRECTS = True
ACCOUNT_LOGIN_ON_PASSWORD_RESET = True
ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = "account_login"


# Configuration SMTP pour l'envoi d'emails
# Email

from pathlib import Path


EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_PORT = os.getenv("EMAIL_PORT", default=465)
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", default=True)
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", default=EMAIL_HOST_USER)
SERVER_EMAIL = DEFAULT_FROM_EMAIL
EMAIL_SUBJECT_PREFIX = "[MassyInnove] "

# Obscur... Pour le bon fonctionnement de l'upload de fichier au niveau conversation...
CSRF_COOKIE_SAMESITE = "None"
CSRF_COOKIE_SECURE = True

# Pour l'import des contacts entrants avec PJ
INGEST_API_KEY = os.environ.get("INGEST_API_KEY", "")
# limite globale (en bytes) du body et des fichiers en mémoire
DATA_UPLOAD_MAX_MEMORY_SIZE = 25 * 1024 * 1024      # 25 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 25 * 1024 * 1024      # 25 MB

if DEBUG:
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    CSRF_COOKIE_SAMESITE = "Lax"