# Generated by Django 5.2.5 on 2025-08-28 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MistralModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('input_cost', models.FloatField(default=0.0, help_text="Coût par token d'entrée", verbose_name="Coût d'entrée")),
                ('output_cost', models.FloatField(default=0.0, help_text='Coût par token de sortie', verbose_name='Coût de sortie')),
            ],
        ),
        migrations.CreateModel(
            name='AgentInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('intro_text', models.TextField(verbose_name='Texte introductif')),
                ('content', models.TextField(verbose_name='Contenu des instructions')),
                ('temperature', models.FloatField(default=0.7, help_text='Valeur pour contrôler la créativité du modèle.', verbose_name='Temperature')),
                ('top_p', models.FloatField(default=0.95, help_text='Valeur pour le nucleus sampling.', verbose_name='Top P')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mistral_model', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='AssistantCR.mistralmodel')),
            ],
        ),
    ]
