# Generated by Django 5.2.5 on 2025-08-28 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AssistantCR', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgentInstruction',
        ),
        migrations.DeleteModel(
            name='MistralModel',
        ),
    ]
